name: Apply Organization Membership
on:
  workflow_dispatch: {}
  schedule:
    # Run this action at the bottom of every hour
    - cron: '30 * * * *'
jobs:
  peribolos:
    runs-on: ubuntu-latest
    container:
      image: gcr.io/k8s-prow/peribolos
    steps:
      - uses: actions/checkout@v3
      - name: Apply ODH organization memebership
        run: |
          echo ${{ secrets.ORG_MANAGEMENT_TOKEN }} > /.github_token.txt
          peribolos --github-token-path /.github_token.txt --config-path "config/opendatahub-io/org.yaml"  --fix-org --fix-org-members --fix-teams --fix-team-members --fix-team-repos --fix-repos --confirm
